 on: 
      push:
        branches:
          - master
    name: 🚀 Deploy website on push
    jobs:
      ftp-web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./public
        steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2.4.0
          working-directory: ./public
          with: 
            fetch-depth: 2
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@4.2.0
          with:
            server: ftpupload.net
            username: thsi_34821928
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: htdocs/
