# Setup
git config git-ftp.url "ftp://ftpupload.net/htdocs/github"
git config git-ftp.user "thsi_34821928"
git config git-ftp.password "79CKbasT"

# Upload all files
git ftp init

# Or if the files are already there
git ftp catchup

# Work and deploy
echo "new content" >> index.txt
git commit index.txt -m "Add new content"
git ftp push
# 1 file to sync:
# [1 of 1] Buffered for upload 'index.txt'.
# Uploading ...
# Last deployment changed to ded01b27e5c785fb251150805308d3d0f8117387.
